name: Deploy to Server

on:
  push:
    branches:
      - new  # Passe dies an deine Hauptbranch an

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Abhängigkeiten installieren und builden
        run: |
          npm install --force
          npm run build

      - name: Dateien per SSH auf den Server übertragen
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/aznw-routes/browser/*"
          target: "/test"
          strip_components: 3
