name: Deploy to Server

on:
  push:
    branches:
      - new  # Passe den Branch an, den du deployen willst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Build (optional)
        run: |
          npm install --force
          npm run build  # Falls du Angular oder ein anderes Build-Tool nutzt

      - name: Deploy via SFTP
        uses: milanmk/actions-file-deployer@1.0.2
        with:
            remote-protocol: "sftp"
            remote-host: ${{ secrets.FTP_SERVER }}
            remote-user: ${{ secrets.FTP_USER }}
            remote-password: ${{ secrets.FTP_PASSWORD }}
            remote-path: "~/test/"
            local-path: "./dist/"
            port: 22      