name: Deploy to Server

on:
  push:
    branches:
      - new  # Passe den Branch an, den du deployen willst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Build (optional)
        run: |
          npm install --force
          npm run build  # Falls du Angular oder ein anderes Build-Tool nutzt

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            port: 22 
            source: "dist/aznw-routes/browser/*"
            target: "~/"
            strip_components: 3